services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api
    restart: unless-stopped
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/textprocessing
      - OLLAMA_BASE_URL=http://ollama:11434
    volumes:
      - ./app:/app/app
      - ./main.py:/app/main.py

    depends_on:
      db:
        condition: service_healthy
      ollama:
        condition: service_started
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000"]
      interval: 30s
      timeout: 10s
      retries: 3
  db:
    image: postgres:15-alpine
    container_name: db
    restart: unless-stopped
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: textprocessing
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 30s
      timeout: 10s
      retries: 3

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    restart: unless-stopped
    ports:
      - "11436:11434"
    volumes:
      - ollama_data:/root/.ollama
    networks:
      - app-network

volumes:
  postgres_data:
  ollama_data:

networks:
  app-network:
    driver: bridge
